updated
rudrapratap63/codeup-week3-assignment-2048_GAME- pull request #2
Opened 2024-09-20 10:23 UTC by rudrapratap63

2024-09-20 11:16 UTC, chandni-codeup requested changes

2024-09-20 11:16 UTC, chandni-codeup commented on Constant.java
> +public class Constant {
file commentry is missing

2024-09-20 11:16 UTC, chandni-codeup commented on CustomStack.java
> +// Create custom stack class for stack data structure
improper commentry

2024-09-20 11:16 UTC, chandni-codeup commented on CustomStack.java
> +    public void push(Game2048.GameState state) {
push ?

2024-09-20 11:16 UTC, chandni-codeup commented on CustomStack.java
> +// for
No documentation

2024-09-20 11:16 UTC, chandni-codeup commented on CustomStack.java
> +    private final Game2048.GameState[] stack;
Why? -> Game248 number cant be there in the class name

2024-09-20 11:16 UTC, chandni-codeup commented on Constant.java
> +    public static String SOUND_NOT_FOUND = "Sound file not found!";
why static ?

2024-09-20 11:16 UTC, chandni-codeup commented on CustomStack.java
> +    // Constructor to initialize the stack with a specific size
why use constructor? not allowed .

2024-09-20 11:16 UTC, chandni-codeup commented on CustomStack.java
> +    public void push(Game2048.GameState state) {
always make an instance for class then use, don't directly use class

2024-09-20 11:16 UTC, chandni-codeup commented on CustomStack.java
> +            stack[++top] = state;
.not a good approach to directly increment/decrement -> fir increment before  then use

2024-09-20 11:16 UTC, chandni-codeup commented on CustomStack.java
> +            return stack[top--];
.not a good approach to directly increment/decrement -> fir decrement before then use

2024-09-20 11:16 UTC, chandni-codeup commented on CustomStack.java
> +
avoid unnecessary spacing

2024-09-20 11:16 UTC, chandni-codeup commented on Game2048.java
> +        int[][] board;
array name must be plural

2024-09-20 11:16 UTC, chandni-codeup commented on Game2048.java
> +    private boolean moved = false;
naming is inappropriate -> 'moved'

2024-09-20 11:16 UTC, chandni-codeup commented on Game2048.java
> +            System.arraycopy(board[i], 0, boardCopy[i], 0, size);
don't use inbuilt methods

2024-09-20 11:16 UTC, chandni-codeup commented on Game2048.java
> +        history.push(new GameState(boardCopy, score));
use instance of the class!!!!!!!

2024-09-20 11:16 UTC, chandni-codeup commented on Game2048.java
> +        try {
mention why you are using try catch, describe exception

2024-09-20 11:16 UTC, chandni-codeup commented on Game2048.java
> +        addTile();
??

2024-09-20 11:16 UTC, chandni-codeup commented on Game2048.java
> +            }
not an optimized approach

2024-09-20 11:16 UTC, chandni-codeup commented on Game2048.java
> +        buttonPanel.add(newGameButton);
variable name!!!!!

2024-09-20 11:16 UTC, chandni-codeup commented on Game2048.java
> +        frame.setVisible(true);
You could have made a method for this

2024-09-20 11:16 UTC, chandni-codeup commented on Game2048.java
> +            // Input - KeyEvent
INDENTATATION!!!!

2024-09-20 11:16 UTC, chandni-codeup commented on Game2048.java
> +                        highScore = Math.max(score, highScore);
No use In-Build method or classes i.e. Math , max()

2024-09-20 11:16 UTC, chandni-codeup commented on Game2048.java
> +                }
INDENTATION can be good

2024-09-20 11:16 UTC, chandni-codeup commented on Game2048.java
> +                        (j > 0 && board[i][j] == board[i][j - 1]) ||
??

2024-09-20 11:16 UTC, chandni-codeup commented on Game2048.java
> +                }
??

2024-09-20 11:16 UTC, chandni-codeup commented on Game2048.java
> +        int randomPosition = (int) (Math.random() * emptyCount);
In-build class and methods should not be used

2024-09-20 11:16 UTC, chandni-codeup commented on Game2048.java
> +                        board[i][j] = (Math.random() < 0.9) ? 2 : 4;
Again MATH , Random

2024-09-20 11:16 UTC, chandni-codeup commented on GamePanel.java
> +    private void drawBoard(Graphics2D graphics2D) {
Improper comment

2024-09-20 11:16 UTC, chandni-codeup commented on GamePanel.java
> +        int x = column * (tileSize + padding) + padding;
Variable name -> x,y????

2024-09-20 11:16 UTC, chandni-codeup commented on GamePanel.java
> +    private Color getTileColor(int value) {
Method  Comments

2024-09-20 11:16 UTC, chandni-codeup commented on SoundPlayer.java
> +// Sound Player for 2048 Game
improper commentry

2024-09-20 11:16 UTC, chandni-codeup commented on SoundPlayer.java
> +        try {
explain exception

2024-09-23 06:34 UTC, rudrapratap63 commented on Constant.java
> +    public static String SOUND_NOT_FOUND = "Sound file not found!";
because we can't print non static variable which is deifine in another class Constant

2024-09-23 06:42 UTC, rudrapratap63 commented on Game2048.java
> +        int[][] board;
because board is singular entity and i initialize only one 2d array which is named as board

2024-09-23 10:04 UTC, closed without merging